---
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2019-2021 Intel Corporation

kernel_arguments: diskencrypt=false release=prod ubuntuversion=focal arch=amd64 username=sys-admin password=P@ssw0rd! epassword=\$6\$RsDAmpXBiF8Ev5ub\$BCEVoMK/MKdUQpJEykScLOgx9S8jw4TZCQyKutCfDQ06Dbk24E1u//ofUWFl39zRTyU8Ex45k634JjNDqCTJh.
